variable "aws_region"           { type = string; default = "us-west-2" }
variable "project_name"         { type = string; default = "devsecops" }
variable "environment"          { type = string; default = "prod" }
variable "vpc_cidr"             { type = string; default = "10.0.0.0/16" }
variable "public_subnet_cidrs"  { type = list(string); default = ["10.0.1.0/24","10.0.2.0/24"] }
variable "private_subnet_cidrs" { type = list(string); default = ["10.0.10.0/24","10.0.11.0/24"] }
variable "availability_zones"   { type = list(string); default = ["us-west-2a","us-west-2b"] }
variable "eks_cluster_version"  { type = string; default = "1.29" }
variable "node_instance_type"   { type = string; default = "t3.medium" }
variable "node_desired_size"    { type = number; default = 3 }
variable "node_min_size"        { type = number; default = 2 }
variable "node_max_size"        { type = number; default = 5 }
variable "ecr_repo_name"        { type = string; default = "devsecops-app" }
